### ISSUE TITLE
ElasticFloatingActionButton supporting LongClickListener 

### ISSUE THREAD

**Issue by Hatzen** [skydoves/ElasticViews#5]
At first thanks for this awesome library :)  
I m using the ElasticFloatingActionButton and it works fine. But i want to apply a LongClickListener to show the user a toast with information what the button is doing.  

I m able to apply the LongClickListener but whenever the button is long pressed the OnClickListener also gets called.
I could not find an easy work around for this problem. Can we have another listener and wait if it consumes the event?

**Comment by skydoves** [comment]
@Hatzen 
Hi, appreciate your interesting and using this library!
I just released version `2.0.4`.
The `LongClickListener` seems working well now.
And many kinds of useless attributes are removed on the new version.
I updated README too, If you have any question anytime please let me know :)
Thank you for your issue!

**Comment by Hatzen** [comment]
Works fine :) and unbelievable fast reaction, thanks a lot!
