### ISSUE TITLE
round attribute

### ISSUE THREAD

**Issue by ArashM98** [skydoves/ElasticViews#7]
hi
good evening

first of all your jobs great. and i thankful for that
please bring back round attribute for buttons. i really liked that. 

thank you

**Comment by skydoves** [comment]
@ArashM98 
Hi, it is released a new version `2.0.6`!
You can use `cornerRadius` attribute on `ElasticButton`, `ElasticCheckButton`, `ElasticLayout` again.
Thank you for your issue :)

**Comment by ArashM98** [comment]
thanks for that friend

and can u set gravity attribute that bring center the drawable that set for drawableTop or drawableLeft?
